### ISSUE TITLE
Build is broken on Darwin with go modules 

### ISSUE THREAD

**Issue by nategadzhi** [gravitational/teleport-plugins#144]
Marking this for myself or @fspmarshall to tackle: 

Build on Darwin is currently broken, but the problem is fixed in https://github.com/moby/term/pull/16. 

```
nate-mbp17:~/g/s/g/g/teleport-plugins master make -C access/slack                                                                                                  (base)
GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build -o build/teleport-slack  -ldflags '-w -s'
# github.com/docker/docker/pkg/term
../../vendor/github.com/docker/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
../../vendor/github.com/docker/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
../../vendor/github.com/docker/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
../../vendor/github.com/docker/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
make: *** [build/teleport-slack] Error 2
nate-mbp17:~/g/s/g/g/teleport-plugins master                                                                                                                       (base)
```

**Comment by nategadzhi** [comment]
@marshall-lee fixed it.
